"""Apply a reviewed cluster-organisation proposal to the database.

The proposal is generated by `cluster_manager.propose_organisation` and
the user picks which actions to apply in the mobile review modal. This
service is the second half of that flow: it validates every action
against the caller's actual data and mutates the DB.

Why we re-validate here even though the agent already validated:
the proposal comes back over the network and a different request brings
it back to apply. We never trust ids from the client — we re-fetch the
user's clusters and tasks and drop any action that references ids the
caller doesn't own. Cheaper than trusting a token-bound payload and
matches how every other write path in the app works.

Actions are processed sequentially in a fixed order so later actions
see the effects of earlier ones (e.g., a move_tasks targeting a cluster
that a previous create_cluster just made). Order:

    1. rename_cluster   (no id changes; safe to run first)
    2. create_cluster   (introduces new cluster ids)
    3. move_tasks       (uses cluster ids that may have just been created)
    4. merge_clusters   (deletes source cluster, must run last)
"""

import logging
from datetime import datetime, timezone
from uuid import UUID, uuid4

from app.db import clusters as clusters_db, tasks as tasks_db
from app.services.cluster_kind import classify_kind

logger = logging.getLogger(__name__)

# Default fallback colour when an action somehow arrives without one.
# Matches the colour the v1 manual cluster-create route uses.
_DEFAULT_COLOR = "#7C6FE0"

_ACTION_ORDER = {
    "rename_cluster": 0,
    "create_cluster": 1,
    "move_tasks": 2,
    "merge_clusters": 3,
}


async def apply_organisation(
    actions: list[dict],
    user_id: UUID,
) -> dict:
    """Apply approved proposal actions to the user's universe.

    Returns a summary describing how many of each action type ran and
    how many were skipped because of validation failures. Routers wrap
    this in the response body so the mobile can surface a toast.

    Any individual action failure is logged and skipped; we never raise
    out — a partial apply is better than no apply, and the mobile
    refetches the universe anyway so the canvas converges.
    """
    # Snapshot the user's current state so every action validates
    # against fresh, owner-bound data. We treat the snapshot as a
    # baseline and update local id sets as we go so subsequent actions
    # can rely on newly-created clusters.
    cluster_rows = await clusters_db.fetch_clusters_for_user(user_id)
    task_rows = await tasks_db.fetch_tasks_for_user(user_id)
    valid_cluster_ids = {str(c["id"]) for c in cluster_rows}
    valid_task_ids = {str(t["id"]) for t in task_rows}

    # Sort by the fixed processing order. Stable sort preserves any
    # client-provided ordering within the same action type, which the
    # review modal uses to honour the LLM's relative ranking.
    ordered = sorted(actions, key=lambda a: _ACTION_ORDER.get(a.get("type"), 99))

    applied = {"create_cluster": 0, "move_tasks": 0, "merge_clusters": 0, "rename_cluster": 0}
    skipped: list[dict] = []

    for action in ordered:
        a_type = action.get("type")
        try:
            if a_type == "rename_cluster":
                ok = await _do_rename(action, user_id, valid_cluster_ids)
            elif a_type == "create_cluster":
                new_id = await _do_create(action, user_id, valid_task_ids)
                if new_id is not None:
                    valid_cluster_ids.add(new_id)
                    ok = True
                else:
                    ok = False
            elif a_type == "move_tasks":
                ok = await _do_move(action, user_id, valid_cluster_ids, valid_task_ids)
            elif a_type == "merge_clusters":
                ok = await _do_merge(action, user_id, valid_cluster_ids)
                if ok:
                    # Source cluster has now been deleted — drop its id.
                    source_id = str(action.get("source_id", ""))
                    valid_cluster_ids.discard(source_id)
            else:
                ok = False
        except Exception as exc:  # noqa: BLE001 — never raise out, log instead
            logger.warning("apply_organisation action %s failed: %s", a_type, exc)
            ok = False

        if ok:
            applied[a_type] = applied.get(a_type, 0) + 1
        else:
            skipped.append({"type": a_type, "action": action})

    return {"applied": applied, "skipped": skipped}


# ---------------------------------------------------------------------------
# Per-action helpers — each returns True on success, False on validation fail
# ---------------------------------------------------------------------------


async def _do_rename(
    action: dict,
    user_id: UUID,
    valid_cluster_ids: set[str],
) -> bool:
    cluster_id = str(action.get("cluster_id", ""))
    new_name = str(action.get("new_name", "")).strip()
    if cluster_id not in valid_cluster_ids or not new_name:
        return False
    row = await clusters_db.update_cluster(UUID(cluster_id), user_id, {"name": new_name})
    return row is not None


async def _do_create(
    action: dict,
    user_id: UUID,
    valid_task_ids: set[str],
) -> str | None:
    """Create a cluster and move the listed tasks into it.

    Returns the new cluster id on success so the caller can extend the
    valid-ids set for any move/merge actions that reference it later.
    """
    name = str(action.get("name", "")).strip()
    color = str(action.get("color", "")).strip() or _DEFAULT_COLOR
    raw_task_ids = action.get("task_ids") or []
    task_ids = [tid for tid in (str(x) for x in raw_task_ids) if tid in valid_task_ids]
    # Same min-2 guardrail the agent applies — never create a cluster
    # for a single task even if the client somehow sent one.
    if not name or len(task_ids) < 2:
        return None

    new_id = uuid4()
    now = datetime.now(timezone.utc)
    payload = {
        "id": str(new_id),
        "owner_id": str(user_id),
        "name": name,
        "summary": None,
        "color": color,
        # LLM-created clusters get the same one-time classification as
        # user-created ones; a later rename won't move them.
        "kind": classify_kind(name),
        "weight_score": 0.0,
        "active_count": len(task_ids),
        "parent_cluster_id": None,
        "created_at": now.isoformat(),
    }
    await clusters_db.insert_cluster(payload)

    # Point each task at the new cluster. We don't recalculate the
    # pressure score here — moving a task between clusters doesn't
    # change its urgency, and skipping the scoring call keeps this
    # transactional (per-task PATCH only).
    for tid in task_ids:
        await tasks_db.update_task(
            UUID(tid),
            user_id,
            {"parent_cluster_id": str(new_id), "updated_at": now.isoformat()},
        )

    return str(new_id)


async def _do_move(
    action: dict,
    user_id: UUID,
    valid_cluster_ids: set[str],
    valid_task_ids: set[str],
) -> bool:
    cluster_id = str(action.get("cluster_id", ""))
    raw_task_ids = action.get("task_ids") or []
    task_ids = [tid for tid in (str(x) for x in raw_task_ids) if tid in valid_task_ids]
    if cluster_id not in valid_cluster_ids or not task_ids:
        return False

    now_iso = datetime.now(timezone.utc).isoformat()
    moved_any = False
    for tid in task_ids:
        row = await tasks_db.update_task(
            UUID(tid),
            user_id,
            {"parent_cluster_id": cluster_id, "updated_at": now_iso},
        )
        if row is not None:
            moved_any = True
    return moved_any


async def _do_merge(
    action: dict,
    user_id: UUID,
    valid_cluster_ids: set[str],
) -> bool:
    """Move every task from source → target, then delete source."""
    source_id = str(action.get("source_id", ""))
    target_id = str(action.get("target_id", ""))
    if source_id == target_id:
        return False
    if source_id not in valid_cluster_ids or target_id not in valid_cluster_ids:
        return False

    # Find every active task in the source cluster and reparent.
    user_tasks = await tasks_db.fetch_tasks_for_user(user_id)
    source_tasks = [t for t in user_tasks if str(t.get("parent_cluster_id")) == source_id]

    now_iso = datetime.now(timezone.utc).isoformat()
    for t in source_tasks:
        await tasks_db.update_task(
            UUID(str(t["id"])),
            user_id,
            {"parent_cluster_id": target_id, "updated_at": now_iso},
        )

    # All tasks moved — drop the source cluster. Tasks already point
    # at target so there's nothing dangling.
    return await clusters_db.delete_cluster(UUID(source_id), user_id)
